version: "3.9"

services:
  api:
    build:
      context: ./real-estate-api
      dockerfile: Dockerfile
      args:
        APP_USER_ID: ${APP_USER_ID}
    container_name: ${API_CONTAINER_NAME}
    ports:
      - "${API_PORT}:3000"
    volumes:
      - ./real-estate-api:/home/realestate-user/real-estate-api
      - /home/realestate-user/real-estate-api/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  frontend:
    build:
      context: ./real-estate-frontend
      dockerfile: Dockerfile
    container_name: real-estate-frontend
    ports:
      - "3001:3000"
    
    # volumes: # For development mode
    #   - ./real-estate-frontend:/app
    #   - /app/node_modules
    #   - /app/.next
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    env_file:
      - .env
    depends_on:
      - api

volumes:
  postgres_data:
